# Replace the text below to customize your site
site_name: Ulises Gordillo Zapana
site_description: My Fabacademy site

site_author: Ulises Gordillo Zapana
docs_dir: docs
site_dir: _site
copyright: Creative Commons Attribution Non Commercial
theme:
  name: material
  # see https://squidfunk.github.io/mkdocs-material/getting-started/#color-palette
  palette:
    primary: "deep"
    accent: "indigo"
  font:
    false
    # text: "Ubuntu"
    # code: "Ubuntu Mono"
  feature:
    tabs: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UlisesGordillo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/UlisesGordilloZ
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ulises-gordillo-zapana-8b3921107
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/ulisesgordillozapana

markdown_extensions:
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
     permalink: true

